import React from 'react';
import { ScenarioResult } from '../../types/dashboard';
import {
  Users,
  TrendingUp,
  ShieldCheck,
  AlertTriangle,
  HelpCircle,
  Clock,
  SlidersHorizontal,
  ChevronRight,
} from 'lucide-react';
import { DataStatusChip } from '../common/DataStatusChip';
import { InfoTooltip } from '../common/InfoTooltip';

interface Props {
  result: ScenarioResult;
  onOpenTechnicalDrawer?: () => void;
}

export const KPIGrid: React.FC<Props> = ({ result, onOpenTechnicalDrawer }) => {
  const isPositiveGuests = result.hotelGuests.diff >= 0;

  const getSupportBadge = () => {
    switch (result.supportLevel) {
      case 'SUPPORTED':
        return {
          businessLabel: 'High Reliability',
          technicalLabel: 'SUPPORTED',
          color: 'text-emerald-800 bg-emerald-50 border-emerald-300',
          icon: ShieldCheck,
          note: 'Direct historical evidence',
          technicalDesc:
            'Model Support Status: SUPPORTED. Scenario capacity and route parameters fall fully within observed historical distribution bounds.',
        };
      case 'LIMITED_SUPPORT':
        return {
          businessLabel: 'Moderate Reliability',
          technicalLabel: 'LIMITED SUPPORT',
          color: 'text-amber-800 bg-amber-50 border-amber-300',
          icon: AlertTriangle,
          note: 'Near boundary of evidence',
          technicalDesc:
            'Model Support Status: LIMITED SUPPORT. Input capacity changes exceed standard historical deviations; estimates carry wider error bands.',
        };
      case 'OUT_OF_SUPPORT':
      default:
        return {
          businessLabel: 'Proxy Estimate',
          technicalLabel: 'OUT OF SUPPORT',
          color: 'text-orange-800 bg-orange-50 border-orange-300',
          icon: HelpCircle,
          note: 'Analogue proxy model',
          technicalDesc:
            'Model Support Status: OUT OF SUPPORT. Route lacks direct historical records; projections rely on analogue proxy routes.',
        };
    }
  };

  const support = getSupportBadge();
  const SupportIcon = support.icon;

  return (
    <div className="space-y-2.5" id="kpi-grid-container">
      {/* Exactly 4 Priority KPI Cards - Height reduced by 30% */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-2.5" id="priority-kpi-grid">
        {/* KPI 1: Predicted New Hotel Arrivals */}
        <div className="p-3.5 rounded-xl bg-white border border-slate-200/90 shadow-2xs flex flex-col justify-between hover:border-slate-300 transition-colors">
          <div>
            <div className="flex items-center justify-between mb-1.5">
              <span className="text-[10.5px] font-bold text-slate-500 uppercase tracking-wider flex items-center gap-1.5 truncate">
                <Users className="w-3.5 h-3.5 text-teal-700 shrink-0" />
                <span>Hotel Arrivals</span>
                <InfoTooltip
                  title="Monthly Hotel Arrivals"
                  businessTerm="Projected commercial hotel check-ins generated by this flight route per month."
                  technicalDefinition="Target metric: Monthly New Hotel Arrivals by nationality modeled through the 5-stage conversion funnel."
                  position="bottom"
                />
              </span>
              <DataStatusChip status="Estimated" size="sm" />
            </div>

            <div className="flex items-baseline gap-1.5 mt-0.5">
              <span className="text-2xl sm:text-[26px] font-extrabold text-slate-900 font-display tracking-tight leading-none">
                {result.hotelGuests.scenario.toLocaleString()}
              </span>
              <span className="text-[11px] text-slate-500 font-medium">/ month</span>
            </div>
          </div>

          <div className="mt-2.5 pt-2 border-t border-slate-100 flex items-center justify-between text-[10.5px] text-slate-500">
            <span>
              Baseline:{' '}
              <strong className="text-slate-800 font-mono">
                {result.hotelGuests.baseline.toLocaleString()}
              </strong>
            </span>
            <span className="text-teal-800 font-semibold font-mono">Pace</span>
          </div>
        </div>

        {/* KPI 2: Change from Baseline */}
        <div className="p-3.5 rounded-xl bg-white border border-slate-200/90 shadow-2xs flex flex-col justify-between hover:border-slate-300 transition-colors">
          <div>
            <div className="flex items-center justify-between mb-1.5">
              <span className="text-[10.5px] font-bold text-slate-500 uppercase tracking-wider flex items-center gap-1.5 truncate">
                <TrendingUp className="w-3.5 h-3.5 text-teal-700 shrink-0" />
                <span>Net Change</span>
                <InfoTooltip
                  title="Net Change in Hotel Guests"
                  businessTerm="Absolute gain or loss in hotel guests compared to the current baseline."
                  technicalDefinition="Delta (Δ) = Scenario Hotel Arrivals − Baseline Hotel Arrivals."
                  position="bottom"
                />
              </span>
              <DataStatusChip status="Derived" size="sm" />
            </div>

            <div className="flex items-baseline gap-1.5 mt-0.5">
              <span
                className={`text-2xl sm:text-[26px] font-extrabold font-display tracking-tight leading-none ${
                  isPositiveGuests ? 'text-teal-800' : 'text-rose-700'
                }`}
              >
                {isPositiveGuests
                  ? `+${result.hotelGuests.diff.toLocaleString()}`
                  : result.hotelGuests.diff.toLocaleString()}
              </span>
              <span className="text-[11px] text-slate-500 font-medium">net guests</span>
            </div>
          </div>

          <div className="mt-2.5 pt-2 border-t border-slate-100 flex items-center justify-between text-[10.5px] text-slate-500">
            <span>
              Seat diff:{' '}
              <strong className="text-slate-800 font-mono">
                {result.totalSeats.diff >= 0
                  ? `+${result.totalSeats.diff.toLocaleString()}`
                  : result.totalSeats.diff.toLocaleString()}
              </strong>
            </span>
            <span className="font-semibold text-slate-600">Net diff</span>
          </div>
        </div>

        {/* KPI 3: Percentage Change */}
        <div className="p-3.5 rounded-xl bg-white border border-slate-200/90 shadow-2xs flex flex-col justify-between hover:border-slate-300 transition-colors">
          <div>
            <div className="flex items-center justify-between mb-1.5">
              <span className="text-[10.5px] font-bold text-slate-500 uppercase tracking-wider flex items-center gap-1 truncate">
                <span>% Change</span>
                <InfoTooltip
                  title="Percentage Change vs Baseline"
                  businessTerm="Proportional increase or decrease in hotel demand resulting from the schedule change."
                  technicalDefinition="Percentage Delta (% Δ) = ((Scenario − Baseline) / Baseline) × 100."
                  position="bottom"
                />
              </span>
              <DataStatusChip status="Derived" size="sm" />
            </div>

            <div className="flex items-baseline gap-1.5 mt-0.5">
              <span
                className={`text-2xl sm:text-[26px] font-extrabold font-display tracking-tight leading-none ${
                  isPositiveGuests ? 'text-teal-800' : 'text-rose-700'
                }`}
              >
                {result.hotelGuests.pct >= 0
                  ? `+${result.hotelGuests.pct.toFixed(1)}%`
                  : `${result.hotelGuests.pct.toFixed(1)}%`}
              </span>
              <span className="text-[11px] text-slate-500 font-medium">vs base</span>
            </div>
          </div>

          <div className="mt-2.5 pt-2 border-t border-slate-100 flex items-center justify-between text-[10.5px] text-slate-500">
            <span>Efficiency:</span>
            <span className="font-mono font-bold text-teal-800">
              {result.guestsPer1kSeats.scenario} / 1k seats
            </span>
          </div>
        </div>

        {/* KPI 4: Forecast Reliability (Replaced technical label "Support Status" with business language) */}
        <div
          className="p-3.5 rounded-xl bg-white border border-slate-200/90 shadow-2xs flex flex-col justify-between hover:border-slate-300 transition-colors"
          id="kpi-forecast-reliability-card"
        >
          <div>
            <div className="flex items-center justify-between mb-1.5">
              <div className="flex items-center gap-1 text-[10.5px] font-bold text-slate-600 uppercase tracking-wider truncate">
                <SupportIcon className="w-3.5 h-3.5 text-teal-700 shrink-0" />
                <span>Forecast Reliability</span>
                {/* Information Tooltip with Technical Definition */}
                <InfoTooltip
                  title="Forecast Reliability"
                  businessTerm="Indicates how confidently this projection is backed by real historical flight and hotel data."
                  technicalDefinition="Model Support Status (SUPPORTED | LIMITED_SUPPORT | OUT_OF_SUPPORT): Measures whether scenario input parameters fall within empirical historical distributions (training convex hull) or require analogue proxy extrapolation."
                  position="bottom"
                />
              </div>
              <span
                className="text-[10px] font-mono font-bold text-slate-700"
                title="Historical Evidence Score (0-100)"
              >
                {result.confidenceScore}/100
              </span>
            </div>

            <div className="my-0.5 flex items-center gap-1.5">
              <span
                className={`inline-flex items-center gap-1 text-[11px] font-bold px-2 py-0.5 rounded-md border uppercase tracking-wider ${support.color}`}
              >
                <SupportIcon className="w-3 h-3 shrink-0" />
                <span>{support.businessLabel}</span>
              </span>
            </div>
          </div>

          <div className="mt-2.5 pt-2 border-t border-slate-100 flex items-center justify-between text-[10.5px] text-slate-500 truncate">
            <span className="truncate">{support.note}</span>
            <span className="font-mono text-[9.5px] text-slate-400">
              ({support.technicalLabel})
            </span>
          </div>
        </div>
      </div>

      {/* Action Bar: Expandable Drawer Trigger & Mandatory Guest Nights notice */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 p-2.5 rounded-xl bg-slate-50 border border-slate-200 text-xs">
        <div className="flex items-center gap-2 text-slate-600 text-[11.5px]">
          <Clock className="w-3.5 h-3.5 text-amber-600 shrink-0" />
          <span>
            <strong className="text-amber-900 font-semibold">Guest Nights — not yet supported</strong> (stay-duration component pending).
          </span>
        </div>

        {onOpenTechnicalDrawer && (
          <button
            id="open-technical-details-btn"
            type="button"
            onClick={onOpenTechnicalDrawer}
            className="self-start sm:self-auto py-1 px-3 rounded-lg bg-white border border-slate-300 hover:border-teal-500 hover:bg-teal-50 text-teal-900 font-bold text-xs flex items-center gap-1.5 shadow-2xs transition-all group shrink-0"
          >
            <SlidersHorizontal className="w-3.5 h-3.5 text-teal-700 group-hover:rotate-12 transition-transform" />
            <span>Technical Details Drawer</span>
            <ChevronRight className="w-3.5 h-3.5 text-teal-600 group-hover:translate-x-0.5 transition-transform" />
          </button>
        )}
      </div>
    </div>
  );
};
