import React, { useState } from 'react';
import { ScenarioResult, RouteInfo } from '../../types/dashboard';
import { ChevronDown, ChevronUp, Layers, Compass, Brain, Database, AlertCircle, Info } from 'lucide-react';

interface Props {
  result: ScenarioResult;
  route: RouteInfo;
}

export const MethodologyDisclosure: React.FC<Props> = ({ result, route }) => {
  const [openSection, setOpenSection] = useState<string | null>(null);

  const toggle = (id: string) => {
    setOpenSection((curr) => (curr === id ? null : id));
  };

  const sections = [
    {
      id: 'aviation',
      title: 'Aviation assumptions',
      icon: Layers,
      summary: 'Flight seats, passenger load factor, and transfer splits',
      content: (
        <div className="space-y-3 text-xs text-stone-600 leading-relaxed">
          <p>
            Scheduled aircraft capacity is converted to onboard passengers using historical route load factor (<strong>{(result.input.useCustomLoadFactor && result.input.customLoadFactor ? result.input.customLoadFactor * 100 : 82.5).toFixed(1)}%</strong>).
          </p>
          <div className="p-3 rounded-xl bg-stone-50 border border-stone-200/60 font-mono text-[11px] text-stone-700">
            Passengers = Scheduled Seats ({result.conversionStages[0]?.scenarioValue.toLocaleString()}) × Load Factor
          </div>
          <p>
            International transit and connecting passengers who do not exit the airport are strictly excluded. Only point-to-point (P2P) terminating visitors enter the Abu Dhabi hotel conversion funnel.
          </p>
        </div>
      ),
    },
    {
      id: 'mapping',
      title: 'Market mapping',
      icon: Compass,
      summary: 'Connecting flight departure origins to hotel nationality data',
      content: (
        <div className="space-y-3 text-xs text-stone-600 leading-relaxed">
          <p>
            Flights departing <strong>{route.departureCity}, {route.departureCountry}</strong> are mapped to the <strong>{route.modelledSourceMarket}</strong> nationality tourism segment.
          </p>
          <div className="p-3 rounded-xl bg-amber-50/70 border border-amber-200/70 text-amber-900 text-xs">
            <strong>Core Governance Rule:</strong> Airport departure country does not equal passport nationality. For instance, London Heathrow flights carry British, American, and international transit passengers. SILA uses empirical correlation weights rather than 1:1 attribution.
          </div>
        </div>
      ),
    },
    {
      id: 'model',
      title: 'Model & benchmark comparison',
      icon: Brain,
      summary: 'linear_v009 regression baseline vs seasonal benchmark',
      content: (
        <div className="space-y-3 text-xs text-stone-600 leading-relaxed">
          <p>
            Projections are generated by the frozen production model <strong>linear_v009</strong> with holdout WMAPE of <strong>25.52%</strong>.
          </p>
          <div className="p-3 rounded-xl bg-stone-50 border border-stone-200/60 grid grid-cols-2 gap-2 text-[11px]">
            <div>
              <span className="text-stone-400 block">linear_v009 WMAPE</span>
              <span className="font-semibold text-stone-900 font-mono">25.52%</span>
            </div>
            <div>
              <span className="text-stone-400 block">Seasonal Benchmark WMAPE</span>
              <span className="font-semibold text-stone-900 font-mono">22.63% (Beat linear)</span>
            </div>
          </div>
          <p>
            The seasonal benchmark achieved superior holdout accuracy, demonstrating that natural annual tourist rhythms are strong drivers alongside airline capacity.
          </p>
        </div>
      ),
    },
    {
      id: 'quality',
      title: 'Data quality & calendar coverage',
      icon: Database,
      summary: '50-month dataset observations and complete-month rules',
      content: (
        <div className="space-y-3 text-xs text-stone-600 leading-relaxed">
          <p>
            Calibrated on 50 observed monthly intervals between January 2022 and February 2026.
          </p>
          <p>
            <strong>Complete Month Rules:</strong> A hotel nationality-month is marked complete only if 100% of calendar days have recorded data. Months with missing days are excluded from target fitting. Null records are strictly preserved and never coerced to zero.
          </p>
        </div>
      ),
    },
    {
      id: 'limitations',
      title: 'Methodological limitations',
      icon: AlertCircle,
      summary: 'Recorded guest-day proxies and non-aviation demand',
      content: (
        <div className="space-y-3 text-xs text-stone-600 leading-relaxed">
          <ul className="list-disc list-inside space-y-1.5 text-stone-600">
            <li>
              <strong>Recorded Guest-Days Proxy:</strong> Multiplies check-ins by historical ratios. It is a recorded guest-day proxy, not verified occupied guest nights or measured length of stay.
            </li>
            <li>
              <strong>Causal Aviation Attribution:</strong> Air capacity changes correlate with hotel demand, but external drivers (visa policies, seasonal events, currency fluctuations) also influence arrivals.
            </li>
            <li>
              <strong>Overland GCC Arrivals:</strong> Visitors driving into Abu Dhabi from neighboring Gulf states (e.g. Oman, Saudi Arabia) appear in hotel registers but not in airport flight manifests.
            </li>
          </ul>
        </div>
      ),
    },
  ];

  return (
    <div className="bg-white rounded-3xl p-6 sm:p-8 border border-stone-200/80 shadow-[0_2px_12px_-4px_rgba(0,0,0,0.04)] space-y-4" id="methodology-progressive-disclosure">
      <div className="space-y-1">
        <h3 className="text-base sm:text-lg font-semibold text-stone-900 tracking-tight">
          How SILA reached this result
        </h3>
        <p className="text-xs text-stone-500 font-normal">
          Explore the evidence chain, underlying model, and empirical rules governing this projection.
        </p>
      </div>

      <div className="divide-y divide-stone-100 border border-stone-200/70 rounded-2xl overflow-hidden bg-white">
        {sections.map((sec) => {
          const isOpen = openSection === sec.id;
          const Icon = sec.icon;

          return (
            <div key={sec.id} className="transition-colors">
              <button
                type="button"
                id={`accordion-btn-${sec.id}`}
                onClick={() => toggle(sec.id)}
                className="w-full p-4 sm:p-4.5 text-left flex items-center justify-between hover:bg-stone-50/70 transition-colors"
              >
                <div className="flex items-center gap-3">
                  <div className="w-8 h-8 rounded-xl bg-stone-100 text-stone-600 flex items-center justify-center shrink-0">
                    <Icon className="w-4 h-4" />
                  </div>
                  <div>
                    <div className="text-xs sm:text-sm font-semibold text-stone-900">
                      {sec.title}
                    </div>
                    <div className="text-[11px] text-stone-400 font-normal hidden sm:block">
                      {sec.summary}
                    </div>
                  </div>
                </div>

                <div className="text-stone-400">
                  {isOpen ? <ChevronUp className="w-4 h-4" /> : <ChevronDown className="w-4 h-4" />}
                </div>
              </button>

              {isOpen && (
                <div className="px-5 pb-5 pt-1 bg-stone-50/40 border-t border-stone-100 animate-in fade-in duration-100">
                  {sec.content}
                </div>
              )}
            </div>
          );
        })}
      </div>
    </div>
  );
};
